services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepassword # Update this password
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://postgres:mysecurepassword@postgres/postgres # Ensure this matches the POSTGRES_PASSWORD
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: